### PR TITLE
Fix Req usage

### PR DESCRIPTION
**Pull request by wojtekmach**
Apologies! 😅

### CODE REVIEW

**Comment by cocoa-xu** [comment]
Oh I see what went wrong! Haha, no worries! I didn't really try it either 🤣🤣🤣

**Comment by wojtekmach** [comment]
Btw given what's left in the Helper module is just caching, it could even be simply:

```elixir
defmodule Helper do
  def download!(url, save_as, overwrite? \\ false) do
    Req.get!(url, http_errors: :raise, output: save_as, cache: not overwrite?)
  end
end
```

though this would always make a _conditional_ GET request. I will have to consider a cache mode that would _not_, if the cache is already warm, which would be nice for offline use.

**Comment by cocoa-xu** [comment]
Wait what, I didn't know I could do this. This is much simpler!

And the `cache_mode` reminds me these policies, perhaps `:req` could consider something similar to these ones? Only a suggestion 😄

> - [NSURLRequestUseProtocolCachePolicy](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestuseprotocolcachepolicy?language=objc)
>  Use the caching logic defined in the protocol implementation, if any, for a particular URL load request.
> - [NSURLRequestReloadIgnoringLocalCacheData](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreloadignoringlocalcachedata?language=objc)
>  The URL load should be loaded only from the originating source.
> - [NSURLRequestReloadIgnoringLocalAndRemoteCacheData](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreloadignoringlocalandremotecachedata?language=objc)
>  Ignore local cache data, and instruct proxies and other intermediates to disregard their caches so far as the protocol allows.
> - [NSURLRequestReloadIgnoringCacheData](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreloadignoringcachedata?language=objc)
>  Replaced by [NSURLRequestReloadIgnoringLocalCacheData](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreloadignoringlocalcachedata?language=objc).
> - [NSURLRequestReturnCacheDataElseLoad](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreturncachedataelseload?language=objc)
>  Use existing cache data, regardless or age or expiration date, loading from originating source only if there is no cached data.
> - [NSURLRequestReturnCacheDataDontLoad](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreturncachedatadontload?language=objc)
>  Use existing cache data, regardless or age or expiration date, and fail if no cached data is available.
> - [NSURLRequestReloadRevalidatingCacheData](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestreloadrevalidatingcachedata?language=objc)
>  Use cache data if the origin source can validate it; otherwise, load from the origin.

https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy?language=objc

**Comment by wojtekmach** [comment]
yup, exactly. Thank you for the reference!

**Pull request merged**
