### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S _build,deps,./lib/generated -L usign`

Let me know if you want to add a GitHub Actions job to this.

### CODE REVIEW

**Comment by cocoa-xu** [comment]
Hi @kianmeng, thanks for fixing these typos. Looks good to me!

**Comment by cocoa-xu** [comment]
> Found via `codespell -S _build,deps,./lib/generated -L usign`
> 
> Let me know if you want to add a GitHub Actions job to this.

I think maybe just adding a pre-push hook should be okay?

**Comment by kianmeng** [comment]
Something like `pre-commit` hook? https://github.com/pre-commit/pre-commit ?

**Comment by cocoa-xu** [comment]
Yes, either a `pre-push` or a `pre-commit` hook should be okay :)

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
