### PR TITLE
Test and examples

### PR DESCRIPTION
**Pull request by cocoa-xu**

### CODE REVIEW

**Comment by cocoa-xu** [comment]
Inconsistent binary size in Nx.BinaryBackend? 

The following issue was first observed in [this CI run](https://github.com/cocoa-xu/evision/runs/4910935732?check_suite_focus=true#step:6:21), which uses OpenCV 4.5.5 and Elixir 1.12.3. However, the test passed for the OpenCV 4.5.4 and Elixir 1.12.3 combination.

[The line](https://github.com/cocoa-xu/evision/blob/18e50a3009fae64fc32b6c3ec615e86dd8cd4597/lib/opencv_nx.ex#L56) leads to the crash is in the `lib/opencv_nx.exs`

```elixir
to_mat(Nx.to_binary(t), Nx.type(t), height, width, channels)
```

`OpenCV.Nx.to_mat` is called in `test/photo_hdr_test.exs` on [this line](https://github.com/cocoa-xu/evision/blob/18e50a3009fae64fc32b6c3ec615e86dd8cd4597/test/photo_hdr_test.exs#L81)

```elixir
    output_ldr_file = Path.join([__DIR__, "photo_hdr_test", "ldr.png"])
    ldr
      |> OpenCV.Nx.to_nx()
      |> Nx.multiply(255)
      |> Nx.clip(0, 255)
      |> Nx.as_type({:u, 8})
      |> OpenCV.Nx.to_mat
      |> then(&OpenCV.imwrite(output_ldr_file, elem(&1, 1)))
```

Adding some output for debugging in `deps/nx/lib/nx/binary_backend.ex` ([line 122](https://github.com/elixir-nx/nx/blob/v0.1.0/nx/lib/nx/binary_backend.ex#L122)),

```elixir
  @impl true
  def to_binary(%{type: {_, size}} = t, limit) do
    limit = limit * div(size, 8)
    IO.puts("limit: #{limit}, size: #{size}")
    binary = to_binary(t)
    IO.puts("binary_size: #{byte_size(binary)}")
```

and some outputs in `test/photo_hdr_test.exs`,
```elixir
    output_ldr_file = Path.join([__DIR__, "photo_hdr_test", "ldr.png"])
    t =
      ldr
      |> OpenCV.Nx.to_nx()
    IO.puts("f32 tensor shape:")
    IO.inspect(Nx.shape(t))
    IO.puts("f32 tensor type:")
    IO.inspect(Nx.type(t))
    t_binary = Nx.to_binary(t)
    IO.puts("f32 tensor binary bytes: #{byte_size(t_binary)}")
    t =
      t
      |> Nx.multiply(255)
      |> Nx.clip(0, 255)
      |> Nx.as_type({:u, 8})
    IO.puts("u8 tensor shape:")
    IO.inspect(Nx.shape(t))
    IO.puts("u8 tensor type:")
    IO.inspect(Nx.type(t))
    t_binary = Nx.to_binary(t)
    IO.puts("tensor binary bytes: #{byte_size(t_binary)}")
    t
      |> OpenCV.Nx.to_mat
      |> then(&OpenCV.imwrite(output_ldr_file, elem(&1, 1)))
```

I can still reproduce this crash on my local machine using the modified code.

```
mix test test/photo_hdr_test.exs --include require_downloading --seed 257445
Excluding tags: [require_ffmpeg: true, dnn: false, ml: false, nx: false, photo: false, video: false]
Including tags: [:require_downloading]

[ WARN:0@2.959] global /home/cocoa/data/evision/3rd_party/opencv/opencv-4.5.5/modules/core/src/matrix_expressions.cpp (1333) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
limit: 1036728, size: 8
binary_size: 1036728
f32 tensor shape:
{714, 484, 3}
f32 tensor type:
{:f, 32}
limit: 4146912, size: 32
binary_size: 4146912
f32 tensor binary bytes: 4146912
u8 tensor shape:
{714, 484, 3}
u8 tensor type:
{:u, 8}
limit: 1036728, size: 8
binary_size: 689277


  1) test High Dynamic Range Imaging (OpenCV.Photo.HDR.Test)
     test/photo_hdr_test.exs:9
     ** (ArgumentError) errors were found at the given arguments:

       * 3rd argument: out of range

     code: t_binary = Nx.to_binary(t)
     stacktrace:
       :erlang.binary_part(<<1, 2, 2, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 2, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, ...>>, 0, 1036728)
       (nx 0.1.0) lib/nx/binary_backend.ex:131: Nx.BinaryBackend.to_binary/2
       test/photo_hdr_test.exs:94: (test)



Finished in 3.7 seconds (0.00s async, 3.7s sync)
1 test, 1 failure

Randomized with seed 257445
```

However, when I pushed the [commit](https://github.com/cocoa-xu/evision/commit/d710d359f2cd161d2b498bded8ba91984cfc2dca) that **only added a few debug prints**, the test [passed](https://github.com/cocoa-xu/evision/actions/runs/1735132803/attempts/1). And it [passed again](https://github.com/cocoa-xu/evision/runs/4911278271?check_suite_focus=true#step:6:28) after I re-run it.

Furthermore, this PR triggered another CI build for the same code, and it [passed](https://github.com/cocoa-xu/evision/actions/runs/1735198905).

@josevalim, sorry for the ping, but perhaps you may have some thoughts about why there were ~30k of binary data missing 
 here...? The tensor that has type `{:f, 32}` is not corrupted. Then it was piped through the following operations

```elixir
      |> Nx.multiply(255)
      |> Nx.clip(0, 255)
      |> Nx.as_type({:u, 8})
```

Up til this point, we still have the correct shape and type information 
```elixir
    IO.puts("u8 tensor shape:")
    IO.inspect(Nx.shape(t))
    IO.puts("u8 tensor type:")
    IO.inspect(Nx.type(t))
```

but binary data seems to be corrupted,
```elixir
    t_binary = Nx.to_binary(t)
```

**Comment by cocoa-xu** [comment]
Re-run the [failed one](https://github.com/cocoa-xu/evision/runs/4910935732?check_suite_focus=true#step:6:21) and now it [passed](https://github.com/cocoa-xu/evision/runs/4911433318?check_suite_focus=true#step:6:18). 

However, some new CI runs were [failed](https://github.com/cocoa-xu/evision/runs/4911451350?check_suite_focus=true#step:6:21) while some [passed](https://github.com/cocoa-xu/evision/runs/4911451659?check_suite_focus=true#step:6:18), even if they were using the same code.

**Comment by josevalim** [comment]
I can think of the following options:

1. The mat has infinity and nans in it which are getting silently filtered

2. Could this be a memory bug somewhere in the NIF?

Here is one idea. Whenever it fails, get the `Nx.to_binary/1` of the original float tensor and save it to disk using `File.write!`. Then, can you reproduce the error by doing `File.read!+Nx.from_binary`? If you can, than this is 100% an Nx issue and I can try to address it if you send me the tensor in disk!

**Comment by cocoa-xu** [comment]
> I can think of the following options:
> 
> 1. The mat has infinity and nans in it which are getting silently filtered
> 2. Could this be a memory bug somewhere in the NIF?
> 
> Here is one idea. Whenever it fails, get the `Nx.to_binary/1` of the original float tensor and save it to disk using `File.write!`. Then, can you reproduce the error by doing `File.read!+Nx.from_binary` and piping it through the rest of the pipeline? If you can, than this is 100% an Nx issue and I can try to address it if you send me the tensor in disk!

Oh, after saving the tensor to disk, I think I can reproduce this issue(?) every time. The code+binary is here, [f32-tensor-to-u8](https://github.com/cocoa-xu/f32-tensor-to-u8). Sorry, GitHub does not allow me to upload `.bin` to the reply, had to set up a repo for this.

**Comment by cocoa-xu** [comment]
I checked the values in C and I found there was a nan at position 689277. Is it possible to change the behaviour...?

```c
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <math.h>

int main(int argc, char *argv[]) {
	int fd = open("f32-tensor.bin", O_RDONLY);
	// 1036728 = 714 * 484 * 3
	size_t size = sizeof(float) * 1036728;
	float * val = (float *)malloc(size);
	if (size == read(fd, val, size)) {
		printf("loaded\r\n");
		for (size_t i = 0; i < size; i++) {
			if (isnan(val[i])) {
				printf("found nan at %ld\r\n", i);
			}
			if (isinf(val[i])) {
				printf("found inf at %ld\r\n", i);
			}
		}
	}
}
```

**Comment by josevalim** [comment]
@cocoa-xu it is definitely a Nx bug then. I just checked numpy and it seems they convert NaNs/Infinity to the lower bound of the new type. I will work on it soon.

**Comment by cocoa-xu** [comment]
> @cocoa-xu it is definitely a Nx bug then. I just checked numpy and it seems they convert NaNs/Infinity to the lower bound of the new type. I will work on it soon.

I just checked the behaviour in OpenCV, and it also converts NaNs/Inf to the lower bound.

```cpp
cv::Mat mat(1, 1, CV_32F);
// set to NAN
mat.at<cv::Vec<float, 1>>(0, 0) << NAN;
std::cout << (mat.at<cv::Vec<float, 1>>(0, 0))[0] << "\n";

// NAN stays as NAN in computation
mat = mat * 255;
std::cout << (mat.at<cv::Vec<float, 1>>(0, 0))[0] << "\n";

// NaNs/Inf gets converted to the lower bound.
mat.convertTo(mat, CV_8U);
std::cout << (int)(mat.at<cv::Vec<uchar, 1>>(0, 0))[0] << "\n";
```

**Comment by cocoa-xu** [comment]
Technically, the code in this PR is "correct"; it just needs nx to improve how NaNs and Infinities are handled when they appear in a tensor. 

Practically, at the moment, users of this library could write the same code and may encounter the same crash even if they are using the code in the main branch. 

Therefore, I'll merge this PR to the main branch, though the chances are that the CI might fail again.

**Comment by josevalim** [comment]
Sorry for the delay. `Nx.as_type` has finally been fixed on the `main` branch and handles conversion from non-finite values to integer types. We will have v0.1.1 out probably this week.

**Comment by cocoa-xu** [comment]
No worries and many thanks for the updates! I'll update the deps and tests once v0.1.1 is released! 😃

**Pull request merged**
